In [ ]:
import numpy as np
import pandas as pd

EDA 데이터셋을 본격적으로 Numpy, Pandas로 분석하기 전에 과제를 통해 손을 푼다고 생각하고 연습해보시면 좋을 것 같습니다!

# 1. Numpy

In [ ]:
# Q1.10~30까지의 정수를 담은 array를 만들어보세요. 이를 a1이라는 변수로 저장하세요
a1 = np.arange(10,31)
print(a1)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [1]:
import numpy as np
import pandas as pd

In [2]:
a1=np.arange(10,31)
print(a1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [ ]:
# Q2. 위에서 만든 array는 shape이 21*1입니다. a1의 shape을 7*3로 바꿔보세요
a1.reshape(7,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [3]:
a1.reshape(7,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [ ]:
# Q3. a1의 array에 있는 값들의 평균과 최댓값을 구해보세요. 세션에서 명확하게 다루지는 않았지만 쉽게 생각해내실 수 있습니다. 모르시면 구글을 활용하세요 

20.0
30


In [4]:
print(a1.mean())
print(a1.max())

20.0
30


In [ ]:
# Q4. 이제는 다차원 배열을 만들어보겠습니다 
# 4*4의 shape을 가지는 다차원 배열을 생성해보세요. 안의 값들은 1부터 채워넣으시면 됩니다. 이를 arr1이라는 변수에 저장하세요


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# Q5. arr1에서 2,6,10,14만 추출하는 코드를 작성해보세요

array([ 2,  6, 10, 14])

In [12]:
arr1[:,1]

array([ 2,  6, 10, 14])

In [ ]:
#Q6. arr1에서 7, 8, 11, 12를 추출하는 코드를 작성해보세요


array([[ 7,  8],
       [11, 12]])

In [13]:
arr1[1:3,2:4]

array([[ 7,  8],
       [11, 12]])

In [ ]:
#Q7. arr1에서 7,15를 추출하는 코드를 작성해보세요


array([ 7, 15])

In [14]:
arr1[[1,3],[2]]

array([ 7, 15])

In [ ]:
#Q8. 아래에 있는 arr2를 arr1 아래에다가 붙여서 arr3을 만들어보세요
arr2 = np.array([[17,18,19,20],[21,22,23,24]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [15]:
arr2 = np.array([[17,18,19,20],[21,22,23,24]])
arr3=np.append(arr1,arr2)
arr3=arr3.reshape(6,4)
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
# Q9. arr3에서 15이상인 값들만 추출하는 코드를 작성해보세요


array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
arr3[arr3>=15]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
# Q10. 1*10의 array를 값이 랜덤이 되게 만들고 그 중에서 최댓값을 0으로 바꿔보세요
# 세션에서 명확하게 다루지 않은 내용입니다. 슬랙에 질문하거나 구글을 활용하시면 좋을 것 같습니다


[0.98350069 0.88479416 0.9764893  0.97436766 0.71021153 0.79987257
 0.3990924  0.73896966 0.14207824 0.1155552 ]
[0.         0.88479416 0.9764893  0.97436766 0.71021153 0.79987257
 0.3990924  0.73896966 0.14207824 0.1155552 ]


In [17]:
x=np.random.rand(1,10)
print(x)

[[0.88697245 0.02231976 0.15493679 0.83793629 0.80400805 0.35657178
  0.08471002 0.3035858  0.01569602 0.50824652]]


In [18]:
x_min=x.min()
x[x==x_min]=0
print(x)

[[0.88697245 0.02231976 0.15493679 0.83793629 0.80400805 0.35657178
  0.08471002 0.3035858  0.         0.50824652]]


# Pandas

In [ ]:
# 준비
# 먼저 타이타닉 데이터셋을 구글 드라이브 마운트 혹은 파일을 경로를 알기 쉬운 곳에 가져와주세요
from google.colab import drive
drive.mount('/content/drive')

In [1]:
import numpy as np
import pandas as pd

In [ ]:
# Q11. Titanic 파일을 불러와 titanic_df라는 변수에 저장하고(저장할 때 첫 번째 열은 index로 지정) 위에서 2개의 행만 출력해보세요


Pclass                              Name     Sex   Age  SibSp  \
PassengerId                                                                  
892               3                  Kelly, Mr. James    male  34.5      0   
893               3  Wilkes, Mrs. James (Ellen Needs)  female  47.0      1   

             Parch  Ticket    Fare Cabin Embarked  
PassengerId                                        
892              0  330911  7.8292   NaN        Q  
893              0  363272  7.0000   NaN        S

In [19]:
titanic_df=pd.read_csv("Titanic.csv", index_col=0)
#Jupyter notebook 이용

In [20]:
titanic_df.head(2)

Pclass                              Name     Sex   Age  SibSp  \
PassengerId                                                                  
892               3                  Kelly, Mr. James    male  34.5      0   
893               3  Wilkes, Mrs. James (Ellen Needs)  female  47.0      1   

             Parch  Ticket    Fare Cabin Embarked  
PassengerId                                        
892              0  330911  7.8292   NaN        Q  
893              0  363272  7.0000   NaN        S

In [ ]:
# Q12. 먼저 결측치를 처리해보겠습니다. 결측치가 하나라도 있는 행은 제거하는 코드를 작성해보세요
# EDA 프로젝트 때는 결측치를 다른 값으로 채우거나 없애는 작업을 할 수 있지만 여기서는 없애고 진행하겠습니다


Pclass                                               Name  \
PassengerId                                                              
904               1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
906               1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
916               1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
918               1                       Ostby, Miss. Helene Ragnhild   
920               1                            Brady, Mr. John Bertram   
...             ...                                                ...   
1296              1                       Frauenthal, Mr. Isaac Gerald   
1297              2       Nourney, Mr. Alfred (Baron von Drachstedt")"   
1299              1                         Widener, Mr. George Dunton   
1303              1    Minahan, Mrs. William Edward (Lillian E Thorpe)   
1306              1                       Oliva y Ocana, Dona. Fermina   

                Sex   Age  SibSp  Parch         Ticket      Fare  \
PassengerId                                                        
904          female  23.0      1      0          21228   82.2667   
906          female  47.0      1      0    W.E.P. 5734   61.1750   
916          female  48.0      1      3       PC 17608  262.3750   
918          female  22.0      0      1         113509   61.9792   
920            male  41.0      0      0         113054   30.5000   
...             ...   ...    ...    ...            ...       ...   
1296           male  43.0      1      0          17765   27.7208   
1297           male  20.0      0      0  SC/PARIS 2166   13.8625   
1299           male  50.0      1      1         113503  211.5000   
1303         female  37.0      1      0          19928   90.0000   
1306         female  39.0      0      0       PC 17758  108.9000   

                       Cabin Embarked  
PassengerId                            
904                      B45        S  
906                      E31        S  
916          B57 B59 B63 B66        C  
918                      B36        C  
920                      A21        S  
...                      ...      ...  
1296                     D40        C  
1297                     D38        C  
1299                     C80        C  
1303                     C78        Q  
1306                    C105        C  

[87 rows x 10 columns]

In [21]:
titanic_df_n=titanic_df.dropna(axis=0)
titanic_df_n

Pclass                                               Name  \
PassengerId                                                              
904               1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
906               1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
916               1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
918               1                       Ostby, Miss. Helene Ragnhild   
920               1                            Brady, Mr. John Bertram   
...             ...                                                ...   
1296              1                       Frauenthal, Mr. Isaac Gerald   
1297              2       Nourney, Mr. Alfred (Baron von Drachstedt")"   
1299              1                         Widener, Mr. George Dunton   
1303              1    Minahan, Mrs. William Edward (Lillian E Thorpe)   
1306              1                       Oliva y Ocana, Dona. Fermina   

                Sex   Age  SibSp  Parch         Ticket      Fare  \
PassengerId                                                        
904          female  23.0      1      0          21228   82.2667   
906          female  47.0      1      0    W.E.P. 5734   61.1750   
916          female  48.0      1      3       PC 17608  262.3750   
918          female  22.0      0      1         113509   61.9792   
920            male  41.0      0      0         113054   30.5000   
...             ...   ...    ...    ...            ...       ...   
1296           male  43.0      1      0          17765   27.7208   
1297           male  20.0      0      0  SC/PARIS 2166   13.8625   
1299           male  50.0      1      1         113503  211.5000   
1303         female  37.0      1      0          19928   90.0000   
1306         female  39.0      0      0       PC 17758  108.9000   

                       Cabin Embarked  
PassengerId                            
904                      B45        S  
906                      E31        S  
916          B57 B59 B63 B66        C  
918                      B36        C  
920                      A21        S  
...                      ...      ...  
1296                     D40        C  
1297                     D38        C  
1299                     C80        C  
1303                     C78        Q  
1306                    C105        C  

[87 rows x 10 columns]

In [ ]:
# Q13. titanic_df에서 가장 어린 승객의 이름과 나이를 구할 수 있는 코드를 작성해보세요
# 답은 여러 개가 있을 수 있습니다. 


Name  Age
PassengerId                                      
1009         Sandstrom, Miss. Beatrice Irene  1.0

In [22]:
youngest=titanic_df_n.sort_values(by='Age', ascending=True, inplace=False)
youngest[['Name','Age']][:1]

Name  Age
PassengerId                                      
1009         Sandstrom, Miss. Beatrice Irene  1.0

In [ ]:
# Q14. Fare 값이 가장 높은 값과 낮은 값의 차이를 구하는 코드를 작성해보세요
# 답은 여러 개가 있을 수 있습니다. 

print('가장 비싼 티켓과 가장 싼 티켓의 가격 차이: $', )

가장 비싼 티켓과 가장 싼 티켓의 가격 차이: $ 512.3292


In [23]:
expensive=titanic_df_n.sort_values(by='Fare', ascending=False, inplace=False)
cheap=titanic_df_n.sort_values(by='Fare', ascending=True, inplace=False)

In [24]:
result=expensive.iloc[0]['Fare']-cheap.iloc[0]['Fare']
print(result)

512.3292


In [ ]:
# Q15. Fare 값 상위 5명의 평균 가격을 계산하는 코드를 작성해보세요


312.61584000000005

In [25]:
print(expensive.iloc[0:5]['Fare'].mean())

312.61584000000005


In [ ]:
# Q16. 타이타닉 승객 중 여성이면서 나이가 40세 이상인 고객들의 정보를 추출하는 코드를 작성해보세요
# 힌트 : 2개의 조건을 동시에 만족할 수 있게 인덱싱하려면 &를 활용하시는 것도 하나의 방법입니다
titanic_df[(titanic_df['Age'] >=40) & (titanic_df['Sex'] == 'female')]

Pclass                                               Name  \
PassengerId                                                              
906               1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
916               1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
936               1   Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)   
940               1    Bucknell, Mrs. William Robert (Emma Eliza Ward)   
961               1                Fortune, Mrs. Mark (Mary McDougald)   
969               1  Cornell, Mrs. Robert Clifford (Malvina Helen L...   
988               1  Cavendish, Mrs. Tyrell William (Julia Florence...   
992               1  Stengel, Mrs. Charles Emil Henry (Annie May Mo...   
1006              1             Straus, Mrs. Isidor (Rosalie Ida Blun)   
1071              1  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...   
1110              1       Widener, Mrs. George Dunton (Eleanor Elkins)   
1131              1        Douglas, Mrs. Walter Donald (Mahala Dutton)   
1197              1  Crosby, Mrs. Edward Gifford (Catherine Elizabe...   
1206              1              White, Mrs. John Stuart (Ella Holmes)   
1235              1  Cardeza, Mrs. James Warburton Martinez (Charlo...   
1242              1       Greenfield, Mrs. Leo David (Blanche Strouse)   
1248              1     Brown, Mrs. John Murray (Caroline Lane Lamson)   
1266              1              Dodge, Mrs. Washington (Ruth Vidaver)   
1283              1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
1289              1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   

                Sex   Age  SibSp  Parch       Ticket      Fare  \
PassengerId                                                      
906          female  47.0      1      0  W.E.P. 5734   61.1750   
916          female  48.0      1      3     PC 17608  262.3750   
936          female  45.0      1      0        11753   52.5542   
940          female  60.0      0      0        11813   76.2917   
961          female  60.0      1      4        19950  263.0000   
969          female  55.0      2      0        11770   25.7000   
988          female  76.0      1      0        19877   78.8500   
992          female  43.0      1      0        11778   55.4417   
1006         female  63.0      1      0     PC 17483  221.7792   
1071         female  64.0      0      2     PC 17756   83.1583   
1110         female  50.0      1      1       113503  211.5000   
1131         female  48.0      1      0     PC 17761  106.4250   
1197         female  64.0      1      1       112901   26.5500   
1206         female  55.0      0      0     PC 17760  135.6333   
1235         female  58.0      0      1     PC 17755  512.3292   
1242         female  45.0      0      1     PC 17759   63.3583   
1248         female  59.0      2      0        11769   51.4792   
1266         female  54.0      1      1        33638   81.8583   
1283         female  51.0      0      1     PC 17592   39.4000   
1289         female  48.0      1      1        13567   79.2000   

                       Cabin Embarked  
PassengerId                            
906                      E31        S  
916          B57 B59 B63 B66        C  
936                      D19        S  
940                      D15        C  
961              C23 C25 C27        S  
969                     C101        S  
988                      C46        S  
992                     C116        C  
1006                 C55 C57        S  
1071                     E45        C  
1110                     C80        C  
1131                     C86        C  
1197                     B26        S  
1206                     C32        C  
1235             B51 B53 B55        C  
1242                 D10 D12        C  
1248                    C101        S  
1266                     A34        S  
1283                     D28        S  
1289                     B41        C

In [26]:
titanic_df_n[(titanic_df_n["Age"]>=40)&(titanic_df_n["Sex"]=="female")]

Pclass                                               Name  \
PassengerId                                                              
906               1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
916               1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
936               1   Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)   
940               1    Bucknell, Mrs. William Robert (Emma Eliza Ward)   
961               1                Fortune, Mrs. Mark (Mary McDougald)   
969               1  Cornell, Mrs. Robert Clifford (Malvina Helen L...   
988               1  Cavendish, Mrs. Tyrell William (Julia Florence...   
992               1  Stengel, Mrs. Charles Emil Henry (Annie May Mo...   
1006              1             Straus, Mrs. Isidor (Rosalie Ida Blun)   
1071              1  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...   
1110              1       Widener, Mrs. George Dunton (Eleanor Elkins)   
1131              1        Douglas, Mrs. Walter Donald (Mahala Dutton)   
1197              1  Crosby, Mrs. Edward Gifford (Catherine Elizabe...   
1206              1              White, Mrs. John Stuart (Ella Holmes)   
1235              1  Cardeza, Mrs. James Warburton Martinez (Charlo...   
1242              1       Greenfield, Mrs. Leo David (Blanche Strouse)   
1248              1     Brown, Mrs. John Murray (Caroline Lane Lamson)   
1266              1              Dodge, Mrs. Washington (Ruth Vidaver)   
1283              1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
1289              1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   

                Sex   Age  SibSp  Parch       Ticket      Fare  \
PassengerId                                                      
906          female  47.0      1      0  W.E.P. 5734   61.1750   
916          female  48.0      1      3     PC 17608  262.3750   
936          female  45.0      1      0        11753   52.5542   
940          female  60.0      0      0        11813   76.2917   
961          female  60.0      1      4        19950  263.0000   
969          female  55.0      2      0        11770   25.7000   
988          female  76.0      1      0        19877   78.8500   
992          female  43.0      1      0        11778   55.4417   
1006         female  63.0      1      0     PC 17483  221.7792   
1071         female  64.0      0      2     PC 17756   83.1583   
1110         female  50.0      1      1       113503  211.5000   
1131         female  48.0      1      0     PC 17761  106.4250   
1197         female  64.0      1      1       112901   26.5500   
1206         female  55.0      0      0     PC 17760  135.6333   
1235         female  58.0      0      1     PC 17755  512.3292   
1242         female  45.0      0      1     PC 17759   63.3583   
1248         female  59.0      2      0        11769   51.4792   
1266         female  54.0      1      1        33638   81.8583   
1283         female  51.0      0      1     PC 17592   39.4000   
1289         female  48.0      1      1        13567   79.2000   

                       Cabin Embarked  
PassengerId                            
906                      E31        S  
916          B57 B59 B63 B66        C  
936                      D19        S  
940                      D15        C  
961              C23 C25 C27        S  
969                     C101        S  
988                      C46        S  
992                     C116        C  
1006                 C55 C57        S  
1071                     E45        C  
1110                     C80        C  
1131                     C86        C  
1197                     B26        S  
1206                     C32        C  
1235             B51 B53 B55        C  
1242                 D10 D12        C  
1248                    C101        S  
1266                     A34        S  
1283                     D28        S  
1289                     B41        C

In [ ]:
# Q17.타이타닉 승객들을 Embarked와 성별을 기준으로 그룹화하고, 각 그룹 별로 평균 나이를 출력해보세요


Embarked        Age
0        C  40.318182
1        C  39.080000
2        Q  37.000000
3        S  38.952381
4        S  38.638889

In [27]:
es=titanic_df_n.groupby(['Embarked','Sex']).mean().reset_index()
es[['Embarked','Age']]

Embarked        Age
0        C  40.318182
1        C  39.080000
2        Q  37.000000
3        S  38.952381
4        S  38.638889

In [ ]:
# Q18. 이제는 3개의 데이터프레임을 병합해보겠습니다
# 먼저 아래 3개의 데이터프레임을 생성하는 코드를 만들어보세요
# 주문 정보 ord_df

CUST_ID ORD_NO PRDT_CD
0     100     11    9001
1     100     12    9002
2     200     13    9001
3     200     14    9003
4     300     15    9003

In [28]:
ord_df=pd.DataFrame([[100,11,9001],[100,12,9002],[200,13,9001],[200,14,9003],[300,15,9003]],
                    index=[0,1,2,3,4], columns=['CUST_ID','ORD_NO','PRDT_CD'])
ord_df

CUST_ID  ORD_NO  PRDT_CD
0      100      11     9001
1      100      12     9002
2      200      13     9001
3      200      14     9003
4      300      15     9003

In [ ]:
# 고객 정보 cust_df

CUST_ID  NAME
0     100   kim
1     200  park
2     300   ahn
3     400  choi

In [29]:
cust_df=pd.DataFrame([[100,'kim'],[200,'park'],[300,'ahn'],[400,'choi']], index=[0,1,2,3], columns=['CUST_ID', 'NAME'])
cust_df

CUST_ID  NAME
0      100   kim
1      200  park
2      300   ahn
3      400  choi

In [ ]:
# 상품정보 prdt_df

PRDT_CD        NM    PRICE
0    9001  Notebook  1000000
1    9002    TABLET  1500000
2    9003        TV  2000000

In [30]:
prdt_df=pd.DataFrame([[9001,'Notebook',1000000],[9002,'TABLET',1500000],[9003,'TV',2000000]],
                     index=[0,1,2], columns=['PRDT_CD', 'NM', 'PRICE'])
prdt_df

PRDT_CD        NM    PRICE
0     9001  Notebook  1000000
1     9002    TABLET  1500000
2     9003        TV  2000000

In [ ]:
# Q19. ord_df와 cust_df를 병합하여 아래와 같은 결과가 나오게 코드를 작성해보세요. ord_cust_df라는 변수로 저장하세요

CUST_ID ORD_NO PRDT_CD  NAME
0     100     11    9001   kim
1     100     12    9002   kim
2     200     13    9001  park
3     200     14    9003  park
4     300     15    9003   ahn

In [31]:
ord_cust_df=pd.merge(ord_df, cust_df, how='left', on='CUST_ID')
ord_cust_df

CUST_ID  ORD_NO  PRDT_CD  NAME
0      100      11     9001   kim
1      100      12     9002   kim
2      200      13     9001  park
3      200      14     9003  park
4      300      15     9003   ahn

In [ ]:
# Q20. 18번에서 만든 데이터프레임과 prdt_df를 병합하여 아래와 같은 결과가 나오게 코드를 작성해보세요. merge_df라는 변수로 저장하세요


CUST_ID ORD_NO PRDT_CD  NAME        NM    PRICE
0     100     11    9001   kim  Notebook  1000000
1     200     13    9001  park  Notebook  1000000
2     100     12    9002   kim    TABLET  1500000
3     200     14    9003  park        TV  2000000
4     300     15    9003   ahn        TV  2000000

In [32]:
merge_df=pd.merge(ord_cust_df, prdt_df, how='right', on='PRDT_CD')
merge_df

CUST_ID  ORD_NO  PRDT_CD  NAME        NM    PRICE
0      100      11     9001   kim  Notebook  1000000
1      200      13     9001  park  Notebook  1000000
2      100      12     9002   kim    TABLET  1500000
3      200      14     9003  park        TV  2000000
4      300      15     9003   ahn        TV  2000000

In [ ]:
#Q21. 19번에서 만든 데이터셋으로 각 고객이 총 얼마를 지불하였는지 보여주는 코드를 작성해보세요


PRICE
NAME         
ahn   2000000
kim   2500000
park  3000000

In [33]:
merge_df.groupby('NAME').sum().reset_index().set_index('NAME')[['PRICE']]

PRICE
NAME         
ahn   2000000
kim   2500000
park  3000000

수고하셨습니다!