In [2]:
import numpy as np
import pandas as pd

EDA 데이터셋을 본격적으로 Numpy, Pandas로 분석하기 전에 과제를 통해 손을 푼다고 생각하고 연습해보시면 좋을 것 같습니다!

# 1. Numpy

In [3]:
# Q1.10~30까지의 정수를 담은 array를 만들어보세요. 이를 a1이라는 변수로 저장하세요
a1 = np.arange(10,31)
print(a1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [4]:
# Q2. 위에서 만든 array는 shape이 21*1입니다. a1의 shape을 7*3로 바꿔보세요
a1.reshape(7,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [5]:
# Q3. a1의 array에 있는 값들의 평균과 최댓값을 구해보세요. 세션에서 명확하게 다루지는 않았지만 쉽게 생각해내실 수 있습니다. 모르시면 구글을 활용하세요
print('Mean: ',a1.mean())
print('Max: ',a1.max())

Mean:  20.0
Max:  30


In [6]:
# Q4. 이제는 다차원 배열을 만들어보겠습니다 
# 4*4의 shape을 가지는 다차원 배열을 생성해보세요. 안의 값들은 1부터 채워넣으시면 됩니다. 이를 arr1이라는 변수에 저장하세요
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [7]:
# Q5. arr1에서 2,6,10,14만 추출하는 코드를 작성해보세요
arr1[:,1]

array([ 2,  6, 10, 14])

In [8]:
#Q6. arr1에서 7, 8, 11, 12를 추출하는 코드를 작성해보세요
arr1[1:3,2:4]

array([[ 7,  8],
       [11, 12]])

In [9]:
#Q7. arr1에서 7,15를 추출하는 코드를 작성해보세요
arr1[[1,3],2]

array([ 7, 15])

In [10]:
#Q8. 아래에 있는 arr2를 arr1 아래에다가 붙여서 arr3을 만들어보세요
arr2 = np.array([[17,18,19,20],[21,22,23,24]])
arr3 = np.append(arr1,arr2,axis=0)
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [11]:
# Q9. arr3에서 15이상인 값들만 추출하는 코드를 작성해보세요
arr3[arr3>=15]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
# Q10. 1*10의 array를 값이 랜덤이 되게 만들고 그 중에서 최댓값을 0으로 바꿔보세요
# 세션에서 명확하게 다루지 않은 내용입니다. 슬랙에 질문하거나 구글을 활용하시면 좋을 것 같습니다
arr4 = np.random.random((1,10))
print(arr4)
arr5 = np.where(arr4==arr4.max(), 0, arr4)
print(arr5)

[[0.32145895 0.46529408 0.43530562 0.95803122 0.13937181 0.51910134
  0.32920618 0.34742121 0.76567184 0.60676512]]
[[0.32145895 0.46529408 0.43530562 0.         0.13937181 0.51910134
  0.32920618 0.34742121 0.76567184 0.60676512]]


# Pandas

In [13]:
# 준비
# 먼저 타이타닉 데이터셋을 구글 드라이브 마운트 혹은 파일을 경로를 알기 쉬운 곳에 가져와주세요
from google.colab import drive
drive.mount('/content/drive')
#jupyter를 사용하여 풀었고, 노트북 파일과 타이타닉 파일을 한 폴더에 넣고 read했습니다.

ModuleNotFoundError: No module named 'google.colab'

In [ ]:
# Q11. Titanic 파일을 불러와 titanic_df라는 변수에 저장하고(저장할 때 첫 번째 열은 index로 지정) 위에서 2개의 행만 출력해보세요
titanic_df = pd.read_csv("Titanic.csv")
titanic_df.head(2)

In [ ]:
# Q12. 먼저 결측치를 처리해보겠습니다. 결측치가 하나라도 있는 행은 제거하는 코드를 작성해보세요
# EDA 프로젝트 때는 결측치를 다른 값으로 채우거나 없애는 작업을 할 수 있지만 여기서는 없애고 진행하겠습니다
titanic_df.dropna(axis=0,inplace=True)

In [ ]:
# Q13. titanic_df에서 가장 어린 승객의 이름과 나이를 구할 수 있는 코드를 작성해보세요
# 답은 여러 개가 있을 수 있습니다. 
y = titanic_df['Age'].idxmin()
titanic_df.loc[y,['Name','Age']]

In [ ]:
# Q14. Fare 값이 가장 높은 값과 낮은 값의 차이를 구하는 코드를 작성해보세요
# 답은 여러 개가 있을 수 있습니다. 
d = titanic_df['Fare'].max()-titanic_df['Fare'].min()
print('가장 비싼 티켓과 가장 싼 티켓의 가격 차이: $',d )

In [ ]:
# Q15. Fare 값 상위 5명의 평균 가격을 계산하는 코드를 작성해보세요
fare_df = titanic_df['Fare']
fare_df = fare_df.sort_values(ascending=False)
fare_df.head(5).mean()

In [ ]:
# Q16. 타이타닉 승객 중 여성이면서 나이가 40세 이상인 고객들의 정보를 추출하는 코드를 작성해보세요
# 힌트 : 2개의 조건을 동시에 만족할 수 있게 인덱싱하려면 &를 활용하시는 것도 하나의 방법입니다
titanic_df[(titanic_df['Age'] >=40) & (titanic_df['Sex'] == 'female')]

In [ ]:
# Q17.타이타닉 승객들을 Embarked와 성별을 기준으로 그룹화하고, 각 그룹 별로 평균 나이를 출력해보세요
group_df = titanic_df.groupby(['Embarked','Sex'])
pd.DataFrame(group_df['Age'].mean())

In [ ]:
# Q18. 이제는 3개의 데이터프레임을 병합해보겠습니다
# 먼저 아래 3개의 데이터프레임을 생성하는 코드를 만들어보세요
# 주문 정보 ord_df
data1 = [[100,11,9001],[100,12,9002],[200,13,9001],[200,14,9003],[300,15,9003]]
ord_df = pd.DataFrame(data1,columns=['CUST_ID','ORD_NO','PRDT_CD'])
ord_df

In [ ]:
# 고객 정보 cust_df
data2 = [[100,'kim'],[200,'park'],[300,'ahn'],[400,'choi']]
cust_df = pd.DataFrame(data2,columns=['CUST_ID','NAME'])
cust_df

In [ ]:
# 상품정보 prdt_df
data3 = [[9001,'Notebook',1000000],[9002,'TABLET',1500000],[9003,'TV',2000000]]
prdt_df = pd.DataFrame(data3,columns=['PRDT_CD','NM','PRICE'])
prdt_df

In [ ]:
# Q19. ord_df와 cust_df를 병합하여 아래와 같은 결과가 나오게 코드를 작성해보세요. ord_cust_df라는 변수로 저장하세요
ord_cust_df = pd.merge(ord_df,cust_df,how='left',on='CUST_ID')
ord_cust_df

In [ ]:
# Q20. 18번에서 만든 데이터프레임과 prdt_df를 병합하여 아래와 같은 결과가 나오게 코드를 작성해보세요. merge_df라는 변수로 저장하세요
merge_df = pd.merge(ord_cust_df,prdt_df,how='outer',on='PRDT_CD')
merge_df

In [ ]:
#Q21. 19번에서 만든 데이터셋으로 각 고객이 총 얼마를 지불하였는지 보여주는 코드를 작성해보세요
ahn_price = merge_df[merge_df['NAME']=='ahn']['PRICE'].sum()
kim_price = merge_df[merge_df['NAME']=='kim']['PRICE'].sum()
park_price = merge_df[merge_df['NAME']=='park']['PRICE'].sum()

data4 = [['ahn',ahn_price],['kim',kim_price],['park',park_price]]
last_df = pd.DataFrame(data4,columns=['NAME','PRICE'])
last_df

수고하셨습니다!