## DSL 9기 기초세션 과제1 (Numpy & Pandas) 이성균

### Numpy

In [15]:
import numpy as np
import pandas as pd

#### Q1.

In [16]:
a1 = np.arange(10,31)
print(a1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


#### Q2.

In [17]:
a1.reshape(7,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

#### Q3.

In [18]:
print(a1.mean())
print(a1.max())

20.0
30


#### Q4.

In [19]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


#### Q5.

In [20]:
arr1[:,1]

array([ 2,  6, 10, 14])

#### Q6.

In [21]:
arr1[1:3,2:4]

array([[ 7,  8],
       [11, 12]])

#### Q7.

In [22]:
arr1[[1,3],[2,2]]

array([ 7, 15])

#### Q8.

In [23]:
arr2 = np.array([[17,18,19,20],[21,22,23,24]])
arr3 = np.append(arr1,arr2,axis=0)
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


#### Q9.

In [24]:
arr3[arr3>=15]

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

#### Q10. np.where() 함수 사용

In [25]:
Q10 = np.random.random(10)
print(Q10)
Q100 = np.where(Q10 == Q10.max(), 0, Q10) #최댓값을 0으로 바꿈
print(Q100)

[0.50567697 0.24097856 0.04479648 0.28089123 0.82133484 0.17314887
 0.86273917 0.43786498 0.55128533 0.87188747]
[0.50567697 0.24097856 0.04479648 0.28089123 0.82133484 0.17314887
 0.86273917 0.43786498 0.55128533 0.        ]


### Pandas

In [29]:
titanic_df = pd.read_csv('C:/DSL_files/Titanic.csv', index_col=0)
titanic_df

Pclass                                          Name     Sex  \
PassengerId                                                                 
892               3                              Kelly, Mr. James    male   
893               3              Wilkes, Mrs. James (Ellen Needs)  female   
894               2                     Myles, Mr. Thomas Francis    male   
895               3                              Wirz, Mr. Albert    male   
896               3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
...             ...                                           ...     ...   
1305              3                            Spector, Mr. Woolf    male   
1306              1                  Oliva y Ocana, Dona. Fermina  female   
1307              3                  Saether, Mr. Simon Sivertsen    male   
1308              3                           Ware, Mr. Frederick    male   
1309              3                      Peter, Master. Michael J    male   

              Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
PassengerId                                                                   
892          34.5      0      0              330911    7.8292   NaN        Q  
893          47.0      1      0              363272    7.0000   NaN        S  
894          62.0      0      0              240276    9.6875   NaN        Q  
895          27.0      0      0              315154    8.6625   NaN        S  
896          22.0      1      1             3101298   12.2875   NaN        S  
...           ...    ...    ...                 ...       ...   ...      ...  
1305          NaN      0      0           A.5. 3236    8.0500   NaN        S  
1306         39.0      0      0            PC 17758  108.9000  C105        C  
1307         38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
1308          NaN      0      0              359309    8.0500   NaN        S  
1309          NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 10 columns]

#### Q11.

In [34]:
titanic_df.head(2)

Pclass                              Name     Sex   Age  SibSp  \
PassengerId                                                                  
892               3                  Kelly, Mr. James    male  34.5      0   
893               3  Wilkes, Mrs. James (Ellen Needs)  female  47.0      1   

             Parch  Ticket    Fare Cabin Embarked  
PassengerId                                        
892              0  330911  7.8292   NaN        Q  
893              0  363272  7.0000   NaN        S

#### Q12.

In [35]:
titanic_df = titanic_df.dropna(axis=0)
titanic_df

Pclass                                               Name  \
PassengerId                                                              
904               1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
906               1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
916               1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
918               1                       Ostby, Miss. Helene Ragnhild   
920               1                            Brady, Mr. John Bertram   
...             ...                                                ...   
1296              1                       Frauenthal, Mr. Isaac Gerald   
1297              2       Nourney, Mr. Alfred (Baron von Drachstedt")"   
1299              1                         Widener, Mr. George Dunton   
1303              1    Minahan, Mrs. William Edward (Lillian E Thorpe)   
1306              1                       Oliva y Ocana, Dona. Fermina   

                Sex   Age  SibSp  Parch         Ticket      Fare  \
PassengerId                                                        
904          female  23.0      1      0          21228   82.2667   
906          female  47.0      1      0    W.E.P. 5734   61.1750   
916          female  48.0      1      3       PC 17608  262.3750   
918          female  22.0      0      1         113509   61.9792   
920            male  41.0      0      0         113054   30.5000   
...             ...   ...    ...    ...            ...       ...   
1296           male  43.0      1      0          17765   27.7208   
1297           male  20.0      0      0  SC/PARIS 2166   13.8625   
1299           male  50.0      1      1         113503  211.5000   
1303         female  37.0      1      0          19928   90.0000   
1306         female  39.0      0      0       PC 17758  108.9000   

                       Cabin Embarked  
PassengerId                            
904                      B45        S  
906                      E31        S  
916          B57 B59 B63 B66        C  
918                      B36        C  
920                      A21        S  
...                      ...      ...  
1296                     D40        C  
1297                     D38        C  
1299                     C80        C  
1303                     C78        Q  
1306                    C105        C  

[87 rows x 10 columns]

#### Q13.

In [46]:
titanic_df.loc[titanic_df['Age']==titanic_df['Age'].min(),['Name','Age']]

Name  Age
PassengerId                                      
1009         Sandstrom, Miss. Beatrice Irene  1.0

#### Q14.

In [50]:
print('가장 비싼 티켓과 가장 싼 티켓의 가격 차이: $', titanic_df['Fare'].max() - titanic_df['Fare'].min())

가장 비싼 티켓과 가장 싼 티켓의 가격 차이: $ 512.3292


#### Q15.

In [55]:
Top5 = titanic_df.sort_values(by='Fare', ascending=False).head(5)
Top5['Fare'].mean()

312.61584000000005

#### Q16.

In [57]:
titanic_df[(titanic_df['Age']>=40)&(titanic_df['Sex']=='female')]

Pclass                                               Name  \
PassengerId                                                              
906               1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
916               1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
936               1   Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)   
940               1    Bucknell, Mrs. William Robert (Emma Eliza Ward)   
961               1                Fortune, Mrs. Mark (Mary McDougald)   
969               1  Cornell, Mrs. Robert Clifford (Malvina Helen L...   
988               1  Cavendish, Mrs. Tyrell William (Julia Florence...   
992               1  Stengel, Mrs. Charles Emil Henry (Annie May Mo...   
1006              1             Straus, Mrs. Isidor (Rosalie Ida Blun)   
1071              1  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...   
1110              1       Widener, Mrs. George Dunton (Eleanor Elkins)   
1131              1        Douglas, Mrs. Walter Donald (Mahala Dutton)   
1197              1  Crosby, Mrs. Edward Gifford (Catherine Elizabe...   
1206              1              White, Mrs. John Stuart (Ella Holmes)   
1235              1  Cardeza, Mrs. James Warburton Martinez (Charlo...   
1242              1       Greenfield, Mrs. Leo David (Blanche Strouse)   
1248              1     Brown, Mrs. John Murray (Caroline Lane Lamson)   
1266              1              Dodge, Mrs. Washington (Ruth Vidaver)   
1283              1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
1289              1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   

                Sex   Age  SibSp  Parch       Ticket      Fare  \
PassengerId                                                      
906          female  47.0      1      0  W.E.P. 5734   61.1750   
916          female  48.0      1      3     PC 17608  262.3750   
936          female  45.0      1      0        11753   52.5542   
940          female  60.0      0      0        11813   76.2917   
961          female  60.0      1      4        19950  263.0000   
969          female  55.0      2      0        11770   25.7000   
988          female  76.0      1      0        19877   78.8500   
992          female  43.0      1      0        11778   55.4417   
1006         female  63.0      1      0     PC 17483  221.7792   
1071         female  64.0      0      2     PC 17756   83.1583   
1110         female  50.0      1      1       113503  211.5000   
1131         female  48.0      1      0     PC 17761  106.4250   
1197         female  64.0      1      1       112901   26.5500   
1206         female  55.0      0      0     PC 17760  135.6333   
1235         female  58.0      0      1     PC 17755  512.3292   
1242         female  45.0      0      1     PC 17759   63.3583   
1248         female  59.0      2      0        11769   51.4792   
1266         female  54.0      1      1        33638   81.8583   
1283         female  51.0      0      1     PC 17592   39.4000   
1289         female  48.0      1      1        13567   79.2000   

                       Cabin Embarked  
PassengerId                            
906                      E31        S  
916          B57 B59 B63 B66        C  
936                      D19        S  
940                      D15        C  
961              C23 C25 C27        S  
969                     C101        S  
988                      C46        S  
992                     C116        C  
1006                 C55 C57        S  
1071                     E45        C  
1110                     C80        C  
1131                     C86        C  
1197                     B26        S  
1206                     C32        C  
1235             B51 B53 B55        C  
1242                 D10 D12        C  
1248                    C101        S  
1266                     A34        S  
1283                     D28        S  
1289                     B41        C

#### Q17.

In [67]:
embarked_group = titanic_df.groupby(['Embarked','Sex'])
embarked_group[['Age']].mean()

Age
Embarked Sex              
C        female  40.318182
         male    39.080000
Q        female  37.000000
S        female  38.952381
         male    38.638889

#### Q18.

In [90]:
ord_df = {'CUST_ID' : [100,100,200,200,300],
           'ORD_NO' : [11,12,13,14,15],
           'PRDT_CD' : [9001,9002,9001,9003,9003]}
ord_df = pd.DataFrame(ord_df)
ord_df

CUST_ID  ORD_NO  PRDT_CD
0      100      11     9001
1      100      12     9002
2      200      13     9001
3      200      14     9003
4      300      15     9003

In [91]:
cust_df = {'CUST_ID' : [100,200,300,400],
          'NAME' : ['kim','park','ahn','choi']}
cust_df = pd.DataFrame(cust_df)
cust_df

CUST_ID  NAME
0      100   kim
1      200  park
2      300   ahn
3      400  choi

In [92]:
prdt_df = {'PRDT_CD' : [9001,9002,9003],
          'NM' : ['Notebook','TABLET','TV'],
          'PRICE' : [1000000,1500000,2000000]}
prdt_df = pd.DataFrame(prdt_df)
prdt_df

PRDT_CD        NM    PRICE
0     9001  Notebook  1000000
1     9002    TABLET  1500000
2     9003        TV  2000000

#### Q19.

In [93]:
ord_cust_df = pd.merge(ord_df, cust_df, how='left', on='CUST_ID')
ord_cust_df

CUST_ID  ORD_NO  PRDT_CD  NAME
0      100      11     9001   kim
1      100      12     9002   kim
2      200      13     9001  park
3      200      14     9003  park
4      300      15     9003   ahn

#### Q20.

In [95]:
merge_df = pd.merge(ord_cust_df,prdt_df)
merge_df

CUST_ID  ORD_NO  PRDT_CD  NAME        NM    PRICE
0      100      11     9001   kim  Notebook  1000000
1      200      13     9001  park  Notebook  1000000
2      100      12     9002   kim    TABLET  1500000
3      200      14     9003  park        TV  2000000
4      300      15     9003   ahn        TV  2000000

#### Q21.

In [98]:
merge_df.groupby('NAME')[['PRICE']].sum()

PRICE
NAME         
ahn   2000000
kim   2500000
park  3000000