In [1]:
import numpy as np
import pandas as pd

EDA 데이터셋을 본격적으로 Numpy, Pandas로 분석하기 전에 과제를 통해 손을 푼다고 생각하고 연습해보시면 좋을 것 같습니다!

# 1. Numpy

In [2]:
# Q1.10~30까지의 정수를 담은 array를 만들어보세요. 이를 a1이라는 변수로 저장하세요
a1 = np.arange(10,31)
print(a1)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [3]:
# Q2. 위에서 만든 array는 shape이 21*1입니다. a1의 shape을 7*3로 바꿔보세요
a1.reshape(7,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [7]:
# Q3. a1의 array에 있는 값들의 평균과 최댓값을 구해보세요. 세션에서 명확하게 다루지는 않았지만 쉽게 생각해내실 수 있습니다. 모르시면 구글을 활용하세요 

print(a1.mean())
print(a1.max())

20.0
30


In [13]:
# Q4. 이제는 다차원 배열을 만들어보겠습니다 
# 4*4의 shape을 가지는 다차원 배열을 생성해보세요. 안의 값들은 1부터 채워넣으시면 됩니다. 이를 arr1이라는 변수에 저장하세요

arr1 = np.arange(1,17)
arr1 = arr1.reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
# Q5. arr1에서 2,6,10,14만 추출하는 코드를 작성해보세요

arr1[:,1]

array([ 2,  6, 10, 14])

In [18]:
#Q6. arr1에서 7, 8, 11, 12를 추출하는 코드를 작성해보세요

arr1[[1,2], 2:]

array([[ 7,  8],
       [11, 12]])

In [16]:
#Q7. arr1에서 7,15를 추출하는 코드를 작성해보세요

arr1[[1,3],2]

array([ 7, 15])

In [20]:
#Q8. 아래에 있는 arr2를 arr1 아래에다가 붙여서 arr3을 만들어보세요
arr2 = np.array([[17,18,19,20],[21,22,23,24]])

arr3 = np.append(arr1, arr2, axis = 0)
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [33]:
# Q9. arr3에서 15이상인 값들만 추출하는 코드를 작성해보세요

arr3 = np.ravel(arr3)
arr3
print(arr3[np.where(arr3 > 14)])

[15 16 17 18 19 20 21 22 23 24]


In [38]:
# Q10. 1*10의 array를 값이 랜덤이 되게 만들고 그 중에서 최댓값을 0으로 바꿔보세요
# 세션에서 명확하게 다루지 않은 내용입니다. 슬랙에 질문하거나 구글을 활용하시면 좋을 것 같습니다

arr4 = np.random.random(10)
arr4[np.where(arr4 == arr4.max())] = 0
arr4

array([0.        , 0.14640241, 0.18778391, 0.38185456, 0.18200811,
       0.7368071 , 0.73731641, 0.03096885, 0.11546253, 0.49372495])

# Pandas

In [39]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# 준비
# 먼저 타이타닉 데이터셋을 구글 드라이브 마운트 혹은 파일을 경로를 알기 쉬운 곳에 가져와주세요
from google.colab import drive
drive.mount('/content/drive')

In [40]:
# Q11. Titanic 파일을 불러와 titanic_df라는 변수에 저장하고(저장할 때 첫 번째 열은 index로 지정) 위에서 2개의 행만 출력해보세요

titanic_df = pd.read_csv('/content/drive/MyDrive/DSL/세션_1/Titanic.csv')
titanic_df.head(2)

PassengerId  Pclass                              Name     Sex   Age  SibSp  \
0          892       3                  Kelly, Mr. James    male  34.5      0   
1          893       3  Wilkes, Mrs. James (Ellen Needs)  female  47.0      1   

   Parch  Ticket    Fare Cabin Embarked  
0      0  330911  7.8292   NaN        Q  
1      0  363272  7.0000   NaN        S

In [43]:
# Q12. 먼저 결측치를 처리해보겠습니다. 결측치가 하나라도 있는 행은 제거하는 코드를 작성해보세요
# EDA 프로젝트 때는 결측치를 다른 값으로 채우거나 없애는 작업을 할 수 있지만 여기서는 없애고 진행하겠습니다

titanic_df.dropna(inplace = True)

In [47]:
# Q13. titanic_df에서 가장 어린 승객의 이름과 나이를 구할 수 있는 코드를 작성해보세요
# 답은 여러 개가 있을 수 있습니다. 

titanic_df[titanic_df['Age'] == titanic_df['Age'].min()]

PassengerId  Pclass                             Name     Sex  Age  SibSp  \
117         1009       3  Sandstrom, Miss. Beatrice Irene  female  1.0      1   

     Parch   Ticket  Fare Cabin Embarked  
117      1  PP 9549  16.7    G6        S

In [48]:
# Q14. Fare 값이 가장 높은 값과 낮은 값의 차이를 구하는 코드를 작성해보세요
# 답은 여러 개가 있을 수 있습니다. 

max_fare = titanic_df['Fare'].max()
min_fare = titanic_df['Fare'].min()

print('가장 비싼 티켓과 가장 싼 티켓의 가격 차이: $', max_fare - min_fare)

가장 비싼 티켓과 가장 싼 티켓의 가격 차이: $ 512.3292


In [54]:
# Q15. Fare 값 상위 5명의 평균 가격을 계산하는 코드를 작성해보세요

titanic_df.sort_values(by = 'Fare', ascending = False).head(5)['Fare'].mean()

312.61584000000005

In [55]:
# Q16. 타이타닉 승객 중 여성이면서 나이가 40세 이상인 고객들의 정보를 추출하는 코드를 작성해보세요
# 힌트 : 2개의 조건을 동시에 만족할 수 있게 인덱싱하려면 &를 활용하시는 것도 하나의 방법입니다

titanic_df[(titanic_df['Age'] >=40) & (titanic_df['Sex'] == 'female')]

PassengerId  Pclass                                               Name  \
14           906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
44           936       1   Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)   
48           940       1    Bucknell, Mrs. William Robert (Emma Eliza Ward)   
69           961       1                Fortune, Mrs. Mark (Mary McDougald)   
77           969       1  Cornell, Mrs. Robert Clifford (Malvina Helen L...   
96           988       1  Cavendish, Mrs. Tyrell William (Julia Florence...   
100          992       1  Stengel, Mrs. Charles Emil Henry (Annie May Mo...   
114         1006       1             Straus, Mrs. Isidor (Rosalie Ida Blun)   
179         1071       1  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...   
218         1110       1       Widener, Mrs. George Dunton (Eleanor Elkins)   
239         1131       1        Douglas, Mrs. Walter Donald (Mahala Dutton)   
305         1197       1  Crosby, Mrs. Edward Gifford (Catherine Elizabe...   
314         1206       1              White, Mrs. John Stuart (Ella Holmes)   
343         1235       1  Cardeza, Mrs. James Warburton Martinez (Charlo...   
350         1242       1       Greenfield, Mrs. Leo David (Blanche Strouse)   
356         1248       1     Brown, Mrs. John Murray (Caroline Lane Lamson)   
374         1266       1              Dodge, Mrs. Washington (Ruth Vidaver)   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   

        Sex   Age  SibSp  Parch       Ticket      Fare            Cabin  \
14   female  47.0      1      0  W.E.P. 5734   61.1750              E31   
24   female  48.0      1      3     PC 17608  262.3750  B57 B59 B63 B66   
44   female  45.0      1      0        11753   52.5542              D19   
48   female  60.0      0      0        11813   76.2917              D15   
69   female  60.0      1      4        19950  263.0000      C23 C25 C27   
77   female  55.0      2      0        11770   25.7000             C101   
96   female  76.0      1      0        19877   78.8500              C46   
100  female  43.0      1      0        11778   55.4417             C116   
114  female  63.0      1      0     PC 17483  221.7792          C55 C57   
179  female  64.0      0      2     PC 17756   83.1583              E45   
218  female  50.0      1      1       113503  211.5000              C80   
239  female  48.0      1      0     PC 17761  106.4250              C86   
305  female  64.0      1      1       112901   26.5500              B26   
314  female  55.0      0      0     PC 17760  135.6333              C32   
343  female  58.0      0      1     PC 17755  512.3292      B51 B53 B55   
350  female  45.0      0      1     PC 17759   63.3583          D10 D12   
356  female  59.0      2      0        11769   51.4792             C101   
374  female  54.0      1      1        33638   81.8583              A34   
391  female  51.0      0      1     PC 17592   39.4000              D28   
397  female  48.0      1      1        13567   79.2000              B41   

    Embarked  
14         S  
24         C  
44         S  
48         C  
69         S  
77         S  
96         S  
100        C  
114        S  
179        C  
218        C  
239        C  
305        S  
314        C  
343        C  
350        C  
356        S  
374        S  
391        S  
397        C

In [58]:
# Q17.타이타닉 승객들을 Embarked와 성별을 기준으로 그룹화하고, 각 그룹 별로 평균 나이를 출력해보세요

titanic_df.groupby('Embarked').mean()['Age']

Embarked
C    39.659574
Q    37.000000
S    38.807692
Name: Age, dtype: float64

In [59]:
# Q18. 이제는 3개의 데이터프레임을 병합해보겠습니다
# 먼저 아래 3개의 데이터프레임을 생성하는 코드를 만들어보세요
# 주문 정보 ord_df

ord_df = pd.DataFrame({'CUST_ID' : [100, 100, 200, 200, 300], 'ORD_NO' : [11 , 12, 13, 14, 15], 'PRDT_CD' : [9001, 9002, 9001, 9003, 9003]})
ord_df

CUST_ID  ORD_NO  PRDT_CD
0      100      11     9001
1      100      12     9002
2      200      13     9001
3      200      14     9003
4      300      15     9003

In [60]:
# 고객 정보 cust_df

cust_df = pd.DataFrame({'CUST_ID' : [100,200,300,400], 'NAME' : ['kim', 'park', 'ahn', 'choi']})
cust_df

CUST_ID  NAME
0      100   kim
1      200  park
2      300   ahn
3      400  choi

In [61]:
# 상품정보 prdt_df

prdt_df = pd.DataFrame({'PRDT_CD' : [9001,9002, 9003], 'NM' : ['Notebook', 'TABLET', 'TV'], 'PRICE' : [1000000, 1500000, 2000000]})
prdt_df

PRDT_CD        NM    PRICE
0     9001  Notebook  1000000
1     9002    TABLET  1500000
2     9003        TV  2000000

In [64]:
# Q19. ord_df와 cust_df를 병합하여 아래와 같은 결과가 나오게 코드를 작성해보세요. ord_cust_df라는 변수로 저장하세요

ord_cust_df = pd.merge(ord_df, cust_df, how = 'left', on = 'CUST_ID')
ord_cust_df

CUST_ID  ORD_NO  PRDT_CD  NAME
0      100      11     9001   kim
1      100      12     9002   kim
2      200      13     9001  park
3      200      14     9003  park
4      300      15     9003   ahn

In [66]:
# Q20. 19번에서 만든 데이터프레임과 prdt_df를 병합하여 아래와 같은 결과가 나오게 코드를 작성해보세요. merge_df라는 변수로 저장하세요

merge_df = pd.merge(ord_cust_df, prdt_df, how = 'left', on = 'PRDT_CD')
merge_df

CUST_ID  ORD_NO  PRDT_CD  NAME        NM    PRICE
0      100      11     9001   kim  Notebook  1000000
1      100      12     9002   kim    TABLET  1500000
2      200      13     9001  park  Notebook  1000000
3      200      14     9003  park        TV  2000000
4      300      15     9003   ahn        TV  2000000

In [67]:
#Q21. 20번에서 만든 데이터셋으로 각 고객이 총 얼마를 지불하였는지 보여주는 코드를 작성해보세요

merge_df.groupby(by = 'NAME')['PRICE'].sum()

NAME
ahn     2000000
kim     2500000
park    3000000
Name: PRICE, dtype: int64

수고하셨습니다!